name: Parse Arguments
description: "A Github Action to parse workflow dispatch arguments."
author: Javier G Gonzalez
inputs:
  arguments:
    description: "Arguments."
    required: false
    default: ""
branding:
  color: "black"
  icon: "package"

runs:
  using: "composite"
  steps:
  - name: Show Arguments
    shell: bash
    run: |
        echo '${{ toJson(github.event.client_payload) }}' > arguments.json
        echo '${{ inputs.arguments }}' > argument_spec.yml
        if [ "$RUNNER_OS" == "Windows" ]; then
          python $GITHUB_ACTION_PATH/action/main.py >> $GITHUB_OUTPUT
        else
          python3 $GITHUB_ACTION_PATH/action/main.py >> $GITHUB_OUTPUT
        fi
