name: Parse Arguments
description: "A Github Action to parse workflow-dispatch arguments."
author: Javier G Gonzalez
inputs:
  arguments:
    description: "Arguments."
    required: true
outputs:
  arguments:
    description: "Parsed arguments."
    value: ${{ steps.parse_arguments.outputs.arguments }}
branding:
  color: "black"
  icon: "package"

runs:
  using: "composite"
  steps:
  - id: parse_arguments
    name: Parse Arguments
    shell: bash
    run: |
        echo '${{ toJson(github.event.client_payload) }}' > arguments.json
        echo '${{ inputs.arguments }}' > argument_spec.yml
        if [ "$RUNNER_OS" == "Windows" ]; then
          python $GITHUB_ACTION_PATH/action/main.py >> $GITHUB_STEP_SUMMARY
        else
          python3 $GITHUB_ACTION_PATH/action/main.py >> $GITHUB_STEP_SUMMARY
        fi
        echo $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
